Update client.cpp (#80)
MY_PATH/cpp_redis-src/sources/core/client.cpp: In member function ‘void cpp_redis::client::sleep_before_next_reconnect_attempt()’:
MY_PATH/cpp_redis-src/sources/core/client.cpp:347:21: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  347 |   std::this_thread::sleep_for(std::chrono::milliseconds(m_reconnect_interval_msecs));

(cherry picked from commit fc2c43fa07e45e1ef0f77cbda6a240e7890ae5aa)